source 'https://gitee.com/hmpff/HMPTools.git'    #个人私有仓库
source 'https://github.com/CocoaPods/Specs.git'  #github仓库

target 'HMPTools_Example' do
  pod 'HMPTools', :path => '../'

  target 'HMPTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
